# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#   Powershell:
#     Psini: 3.1.3
#
#  Name:
#    spl_map_ldap_roles.yml
#
#  Description:
#    Mapping built-in Splunk groups with LDAP groups
#
#  Input:
#    spl_home_dir # Path to Splunk home dir; Default 'C:\Program Files\Splunk'; Taken from inventory
#    spl_ldap_name # LDAP stanza name
#    spl_ldap_admin_group # May be $null
#    spl_ldap_can_delete_group # May be $null
#    spl_ldap_power_group # May be $null
#    spl_ldap_user_group # May be $null
#    spl_ldap_ssr_group # May be $null
#    spl_skip_restart # 1 - yes; 0 - no; Restart is required but you can skip it
#
#  Output:
#    -
#
#  Requirements:
#    Powershell module:
#      Psini

---

- name: 'SPL :: Mapping roles with LDAP groups by editing {{ spl_home_dir }}\etc\system\local\authentication.conf'
  include_tasks: ../ansible_play/windows/windows_edit_ini.yml
  vars:
    ini_section: 'roleMap_{{ spl_ldap_name }}'
    #ini_section: '{{ item.section }}'
    ini_option: '{{ item.option }}'
    ini_value: '{{ item.value }}'
    ini_path: '{{ spl_home_dir }}\etc\system\local\authentication.conf'
    ini_mode: 'set'
  loop:
    - { section: '', option: 'admin', value: '{{ spl_ldap_admin_group }}' }
    - { section: '', option: 'can_delete', value: '{{ spl_ldap_can_delete_group }}' }
    - { section: '', option: 'power', value: '{{ spl_ldap_power_group }}' }
    - { section: '', option: 'user', value: '{{ spl_ldap_user_group }}' }
    - { section: '', option: 'splunk-system-role', value: '{{ spl_ldap_ssr_group }}' }
  loop_control:
    index_var: loop_idx

- import_tasks: ./spl_manage_service.yml
  vars:
    spl_service_action: 'restart'
  when: spl_skip_restart == 0