# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#   Powershell:
#     Psini: 3.1.3
#
#  Name:
#    spl_configure_deployer.yml
#
#  Description:
#    Configuring Splunk Deployer role
#
#  Input:
#    spl_home_dir # Path to Splunk home dir; Default 'C:\Program Files\Splunk'; Taken from inventory
#    spl_sh—Å_key # Search head cluster security key
#    spl_shc_label # Name of Search Head cluster; Must be the same on each cluster member
#    spl_skip_restart # 1 - yes; 0 - no; Restart is required but you can skip it
#      
#  Output:
#    -
#
#  Requirements:
#    Run only on server which selected as deployer
#    Splunk executable dir in PATH
#    Powershell module:
#      Psini

- name: 'SPL :: Configuring Deployer'
  debug:
    msg: 'Performing tasks to configure Deployer'

- name: 'SPL :: Configuring {{ spl_home_dir }}\etc\system\local\server.conf'
  include_tasks: ./windows/windows_edit_ini.yml
  vars:
    ini_section: 'shclustering'
    ini_option: '{{ item.option }}'
    ini_value: '{{ item.value }}'
    ini_path: '{{ spl_home_dir }}\etc\system\local\server.conf'
    ini_mode: 'set'
  loop:
  - { section: '', option: 'pass4SymmKey', value: '{{ spl_shc_key }}' }
  - { section: '', option: 'shcluster_label', value: '{{ spl_shc_label }}' }
  loop_control:
    index_var: loop_idx

- import_tasks: ./spl_manage_service.yml
  vars:
    spl_service_action: 'restart'
  when: spl_skip_restart == 0
