# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#   Powershell:
#     Psini: 3.1.3
#
#  Name:
#    spl_ldap_enable_auth.yml
#
#  Description:
#    Enabling added LDAP stanza(s)
#
#  Input:
#    spl_home_dir # Path to Splunk home dir; Default 'C:\Program Files\Splunk'; Taken from inventory
#    spl_ldap_names_enable # List of LDAP stanza names separated by comma which need to be enable
#    spl_skip_restart # 1 - yes; 0 - no; Restart is required but you can skip it
#
#  Output:
#    -
#
#  Requirements:
#    Powershell module:
#      Psini

---

- name: 'SPL :: Mapping roles with LDAP groups by editing {{ spl_home_dir }}\etc\system\local\authentication.conf'
  include_tasks: ./windows/windows_edit_ini.yml
  vars:
    ini_section: 'authentication'
    #ini_section: '{{ item.section }}'
    ini_option: '{{ item.option }}'
    ini_value: '{{ item.value }}'
    ini_path: '{{ spl_home_dir }}\etc\system\local\authentication.conf'
    ini_mode: 'set'
  loop:
    - { section: '', option: 'authSettings', value: '{{ spl_ldap_names_enable }}' }
    - { section: '', option: 'authType', value: 'LDAP' }
  loop_control:
    index_var: loop_idx

- import_tasks: ./spl_manage_service.yml
  vars:
    spl_service_action: 'restart'
  when: spl_skip_restart == 0