# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#
#  Name:
#    spl_add_path.yml
#
#  Description:
#    Adding Splunk executable dir to path
#    After this you can call splunk from CMD or Powershell
#
#  Input:
#    spl_home_dir # Path to Splunk home dir; Default 'C:\Program Files\Splunk'; Taken from inventory
#      
#  Output:
#    -

---
      
- name: 'SLP :: Adding SPL dir to PATH'
  #ansible.windows.win_path
  win_path:
    elements: '{{ spl_home_dir }}\bin'