# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#   Powershell:
#     Psini: 3.1.3
#
#  Name:
#    spl_configure_shc_member.yml
#
#  Description:
#    Configuring Indexer cluster members
#    Search head cluster sercet set directly
#    Using 'secret' option in 'init shcluster-config' command cause to password mismatch with Deployer
#    Link to post: https://community.splunk.com/t5/Deployment-Architecture/Error-while-applying-shcluster-bundle-on-deployer/m-p/628236
#
#  Input:
#    spl_home_dir # Path to Splunk home dir; Default 'C:\Program Files\Splunk'; Taken from inventory
#    spl_management_port # Splunk management port; Default 8089
#    spl_shc_key # Indexer cluster security key
#    spl_shc_label # Name of Search Head cluster; Must be the same on each cluster member
#    spl_shc_rep_factor # Replication factor of indexer cluster; Equals number of sh instances in cluster
#    spl_shc_rep_port # Search head cluster replication port; Default 9777
#    spl_username # Splunk admin account
#    spl_password #
#    spl_skip_restart # 1 - yes; 0 - no; Restart is required but you can skip it
#      
#  Output:
#    -
#
#  Requirements:
#    Run only on server(s) which selected as search head cluster member
#    Splunk executable dir in PATH
#    Powershell module:
#      Psini


- name: 'SPL :: Collecting Deployer group'
  set_fact:
    spl_deployer_group: '{{ (group_names | last).split("_")[:-1] | join ("_") }}_shd'

- name: 'SPL :: Setting Deployer and SHC member uris'
  set_fact:
    spl_deployer_uri: 'https://{{ groups[spl_deployer_group][0] }}:{{ spl_management_port }}'
    spl_shc_member_uri: 'https://{{ ansible_fqdn }}:{{ spl_management_port }}'
    
- name: 'SPL :: Configuring Search head cluster member'
  #ansible.windows.win_shell
  win_shell: |
    splunk init shcluster-config -auth '{{ spl_username }}:{{ spl_password }}' -mgmt_uri '{{ spl_shc_member_uri }}' -replication_port '{{ spl_shc_rep_port }}' -replication_factor '{{ spl_shc_rep_factor }}' -conf_deploy_fetch_url '{{ spl_deployer_uri }}' -shcluster_label '{{ spl_shc_label }}'

- name: 'SPL :: Editing {{ spl_home_dir }}\etc\system\local\server.conf'
  include_tasks: ../ansible_play/windows/windows_edit_ini.yml
  vars:
    ini_section: 'shclustering'
    #ini_section: '{{ item.section }}'
    ini_option: '{{ item.option }}'
    ini_value: '{{ item.value }}'
    ini_path: '{{ spl_home_dir }}\etc\system\local\server.conf'
    ini_mode: 'set'
  loop:
    - { section: '', option: 'pass4SymmKey', value: '{{ spl_shc_key }}' }
  loop_control:
    index_var: loop_idx

- import_tasks: ./spl_manage_service.yml
  vars:
    spl_service_action: 'restart'
  when: spl_skip_restart == 0