# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#
#  Name:
#    spl_create_local_user.yml
#
#  Description:
#    Creating local user
#
#  Input:
#    spl_local_user # Username of new user
#    spl_local_password #
#    spl_local_role # Role name which exist
#    spl_username # Splunk admin account
#    spl_password #
#      
#  Output:
#    -
#

---

- name: 'SPL :: Creating local user {{ spl_local_user }}'
  #ansible.windows.win_shell
  win_shell: |
    splunk add user '{{ spl_local_user }}' -password '{{ spl_local_password }}' -role '{{ spl_local_role }}' -auth '{{ spl_username }}:{{ spl_password }}'