# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#
#  Name:
#    spl_bring_shc_captain.yml
#
#  Description:
#    Bringing up Search head cluster captain
#
#  Input:
#    spl_management_port # Splunk management port; Default 8089
#    spl_username # Splunk admin account
#    spl_password #
#      
#  Output:
#    -
#
#
#  Requirements:
#    Run only on server(s) which selected as search head cluster member

- name: 'SPL :: Creating Search head members list'
  set_fact:
    spl_shc_uris: "{{ spl_shc_uris_temp | map('regex_replace', '$', ':%s' % spl_management_port) | list | join (',')}}"
  vars:
    spl_shc_uris_temp: "{{ groups[group_names | last] | map('regex_replace', '^', 'https://') | list }}"

- name: 'SPL :: Defining Search head cluster captain'
  set_fact:
    spl_shc_captain_fqdn: '{{ (groups[group_names | last])[0] }}'

- name: 'SPL :: Bringing up Search head cluster captain'
  #ansible.windows.win_shell
  win_shell: |
    splunk bootstrap shcluster-captain -servers_list '{{ spl_shc_uris }}' -auth '{{ spl_username }}:{{ spl_password }}'
  when: 'ansible_fqdn == spl_shc_captain_fqdn'